// Code generated by ent, DO NOT EDIT.

package repository

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldName, v))
}

// FullName applies equality check predicate on the "full_name" field. It's identical to FullNameEQ.
func FullName(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldFullName, v))
}

// OwnerLogin applies equality check predicate on the "owner_login" field. It's identical to OwnerLoginEQ.
func OwnerLogin(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldOwnerLogin, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDescription, v))
}

// Private applies equality check predicate on the "private" field. It's identical to PrivateEQ.
func Private(v bool) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldPrivate, v))
}

// Archived applies equality check predicate on the "archived" field. It's identical to ArchivedEQ.
func Archived(v bool) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldArchived, v))
}

// Disabled applies equality check predicate on the "disabled" field. It's identical to DisabledEQ.
func Disabled(v bool) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDisabled, v))
}

// HTMLURL applies equality check predicate on the "html_url" field. It's identical to HTMLURLEQ.
func HTMLURL(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldHTMLURL, v))
}

// DefaultBranch applies equality check predicate on the "default_branch" field. It's identical to DefaultBranchEQ.
func DefaultBranch(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDefaultBranch, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLanguage, v))
}

// StargazersCount applies equality check predicate on the "stargazers_count" field. It's identical to StargazersCountEQ.
func StargazersCount(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldStargazersCount, v))
}

// ForksCount applies equality check predicate on the "forks_count" field. It's identical to ForksCountEQ.
func ForksCount(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldForksCount, v))
}

// OpenIssuesCount applies equality check predicate on the "open_issues_count" field. It's identical to OpenIssuesCountEQ.
func OpenIssuesCount(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldOpenIssuesCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldUpdatedAt, v))
}

// PushedAt applies equality check predicate on the "pushed_at" field. It's identical to PushedAtEQ.
func PushedAt(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldPushedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldName, v))
}

// FullNameEQ applies the EQ predicate on the "full_name" field.
func FullNameEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldFullName, v))
}

// FullNameNEQ applies the NEQ predicate on the "full_name" field.
func FullNameNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldFullName, v))
}

// FullNameIn applies the In predicate on the "full_name" field.
func FullNameIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldFullName, vs...))
}

// FullNameNotIn applies the NotIn predicate on the "full_name" field.
func FullNameNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldFullName, vs...))
}

// FullNameGT applies the GT predicate on the "full_name" field.
func FullNameGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldFullName, v))
}

// FullNameGTE applies the GTE predicate on the "full_name" field.
func FullNameGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldFullName, v))
}

// FullNameLT applies the LT predicate on the "full_name" field.
func FullNameLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldFullName, v))
}

// FullNameLTE applies the LTE predicate on the "full_name" field.
func FullNameLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldFullName, v))
}

// FullNameContains applies the Contains predicate on the "full_name" field.
func FullNameContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldFullName, v))
}

// FullNameHasPrefix applies the HasPrefix predicate on the "full_name" field.
func FullNameHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldFullName, v))
}

// FullNameHasSuffix applies the HasSuffix predicate on the "full_name" field.
func FullNameHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldFullName, v))
}

// FullNameEqualFold applies the EqualFold predicate on the "full_name" field.
func FullNameEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldFullName, v))
}

// FullNameContainsFold applies the ContainsFold predicate on the "full_name" field.
func FullNameContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldFullName, v))
}

// OwnerLoginEQ applies the EQ predicate on the "owner_login" field.
func OwnerLoginEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldOwnerLogin, v))
}

// OwnerLoginNEQ applies the NEQ predicate on the "owner_login" field.
func OwnerLoginNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldOwnerLogin, v))
}

// OwnerLoginIn applies the In predicate on the "owner_login" field.
func OwnerLoginIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldOwnerLogin, vs...))
}

// OwnerLoginNotIn applies the NotIn predicate on the "owner_login" field.
func OwnerLoginNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldOwnerLogin, vs...))
}

// OwnerLoginGT applies the GT predicate on the "owner_login" field.
func OwnerLoginGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldOwnerLogin, v))
}

// OwnerLoginGTE applies the GTE predicate on the "owner_login" field.
func OwnerLoginGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldOwnerLogin, v))
}

// OwnerLoginLT applies the LT predicate on the "owner_login" field.
func OwnerLoginLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldOwnerLogin, v))
}

// OwnerLoginLTE applies the LTE predicate on the "owner_login" field.
func OwnerLoginLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldOwnerLogin, v))
}

// OwnerLoginContains applies the Contains predicate on the "owner_login" field.
func OwnerLoginContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldOwnerLogin, v))
}

// OwnerLoginHasPrefix applies the HasPrefix predicate on the "owner_login" field.
func OwnerLoginHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldOwnerLogin, v))
}

// OwnerLoginHasSuffix applies the HasSuffix predicate on the "owner_login" field.
func OwnerLoginHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldOwnerLogin, v))
}

// OwnerLoginEqualFold applies the EqualFold predicate on the "owner_login" field.
func OwnerLoginEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldOwnerLogin, v))
}

// OwnerLoginContainsFold applies the ContainsFold predicate on the "owner_login" field.
func OwnerLoginContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldOwnerLogin, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldDescription, v))
}

// PrivateEQ applies the EQ predicate on the "private" field.
func PrivateEQ(v bool) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldPrivate, v))
}

// PrivateNEQ applies the NEQ predicate on the "private" field.
func PrivateNEQ(v bool) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldPrivate, v))
}

// ArchivedEQ applies the EQ predicate on the "archived" field.
func ArchivedEQ(v bool) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldArchived, v))
}

// ArchivedNEQ applies the NEQ predicate on the "archived" field.
func ArchivedNEQ(v bool) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldArchived, v))
}

// DisabledEQ applies the EQ predicate on the "disabled" field.
func DisabledEQ(v bool) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDisabled, v))
}

// DisabledNEQ applies the NEQ predicate on the "disabled" field.
func DisabledNEQ(v bool) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldDisabled, v))
}

// HTMLURLEQ applies the EQ predicate on the "html_url" field.
func HTMLURLEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldHTMLURL, v))
}

// HTMLURLNEQ applies the NEQ predicate on the "html_url" field.
func HTMLURLNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldHTMLURL, v))
}

// HTMLURLIn applies the In predicate on the "html_url" field.
func HTMLURLIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldHTMLURL, vs...))
}

// HTMLURLNotIn applies the NotIn predicate on the "html_url" field.
func HTMLURLNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldHTMLURL, vs...))
}

// HTMLURLGT applies the GT predicate on the "html_url" field.
func HTMLURLGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldHTMLURL, v))
}

// HTMLURLGTE applies the GTE predicate on the "html_url" field.
func HTMLURLGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldHTMLURL, v))
}

// HTMLURLLT applies the LT predicate on the "html_url" field.
func HTMLURLLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldHTMLURL, v))
}

// HTMLURLLTE applies the LTE predicate on the "html_url" field.
func HTMLURLLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldHTMLURL, v))
}

// HTMLURLContains applies the Contains predicate on the "html_url" field.
func HTMLURLContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldHTMLURL, v))
}

// HTMLURLHasPrefix applies the HasPrefix predicate on the "html_url" field.
func HTMLURLHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldHTMLURL, v))
}

// HTMLURLHasSuffix applies the HasSuffix predicate on the "html_url" field.
func HTMLURLHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldHTMLURL, v))
}

// HTMLURLIsNil applies the IsNil predicate on the "html_url" field.
func HTMLURLIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldHTMLURL))
}

// HTMLURLNotNil applies the NotNil predicate on the "html_url" field.
func HTMLURLNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldHTMLURL))
}

// HTMLURLEqualFold applies the EqualFold predicate on the "html_url" field.
func HTMLURLEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldHTMLURL, v))
}

// HTMLURLContainsFold applies the ContainsFold predicate on the "html_url" field.
func HTMLURLContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldHTMLURL, v))
}

// DefaultBranchEQ applies the EQ predicate on the "default_branch" field.
func DefaultBranchEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldDefaultBranch, v))
}

// DefaultBranchNEQ applies the NEQ predicate on the "default_branch" field.
func DefaultBranchNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldDefaultBranch, v))
}

// DefaultBranchIn applies the In predicate on the "default_branch" field.
func DefaultBranchIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldDefaultBranch, vs...))
}

// DefaultBranchNotIn applies the NotIn predicate on the "default_branch" field.
func DefaultBranchNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldDefaultBranch, vs...))
}

// DefaultBranchGT applies the GT predicate on the "default_branch" field.
func DefaultBranchGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldDefaultBranch, v))
}

// DefaultBranchGTE applies the GTE predicate on the "default_branch" field.
func DefaultBranchGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldDefaultBranch, v))
}

// DefaultBranchLT applies the LT predicate on the "default_branch" field.
func DefaultBranchLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldDefaultBranch, v))
}

// DefaultBranchLTE applies the LTE predicate on the "default_branch" field.
func DefaultBranchLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldDefaultBranch, v))
}

// DefaultBranchContains applies the Contains predicate on the "default_branch" field.
func DefaultBranchContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldDefaultBranch, v))
}

// DefaultBranchHasPrefix applies the HasPrefix predicate on the "default_branch" field.
func DefaultBranchHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldDefaultBranch, v))
}

// DefaultBranchHasSuffix applies the HasSuffix predicate on the "default_branch" field.
func DefaultBranchHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldDefaultBranch, v))
}

// DefaultBranchEqualFold applies the EqualFold predicate on the "default_branch" field.
func DefaultBranchEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldDefaultBranch, v))
}

// DefaultBranchContainsFold applies the ContainsFold predicate on the "default_branch" field.
func DefaultBranchContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldDefaultBranch, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.Repository {
	return predicate.Repository(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageIsNil applies the IsNil predicate on the "language" field.
func LanguageIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldLanguage))
}

// LanguageNotNil applies the NotNil predicate on the "language" field.
func LanguageNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldLanguage))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.Repository {
	return predicate.Repository(sql.FieldContainsFold(FieldLanguage, v))
}

// StargazersCountEQ applies the EQ predicate on the "stargazers_count" field.
func StargazersCountEQ(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldStargazersCount, v))
}

// StargazersCountNEQ applies the NEQ predicate on the "stargazers_count" field.
func StargazersCountNEQ(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldStargazersCount, v))
}

// StargazersCountIn applies the In predicate on the "stargazers_count" field.
func StargazersCountIn(vs ...int32) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldStargazersCount, vs...))
}

// StargazersCountNotIn applies the NotIn predicate on the "stargazers_count" field.
func StargazersCountNotIn(vs ...int32) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldStargazersCount, vs...))
}

// StargazersCountGT applies the GT predicate on the "stargazers_count" field.
func StargazersCountGT(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldStargazersCount, v))
}

// StargazersCountGTE applies the GTE predicate on the "stargazers_count" field.
func StargazersCountGTE(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldStargazersCount, v))
}

// StargazersCountLT applies the LT predicate on the "stargazers_count" field.
func StargazersCountLT(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldStargazersCount, v))
}

// StargazersCountLTE applies the LTE predicate on the "stargazers_count" field.
func StargazersCountLTE(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldStargazersCount, v))
}

// ForksCountEQ applies the EQ predicate on the "forks_count" field.
func ForksCountEQ(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldForksCount, v))
}

// ForksCountNEQ applies the NEQ predicate on the "forks_count" field.
func ForksCountNEQ(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldForksCount, v))
}

// ForksCountIn applies the In predicate on the "forks_count" field.
func ForksCountIn(vs ...int32) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldForksCount, vs...))
}

// ForksCountNotIn applies the NotIn predicate on the "forks_count" field.
func ForksCountNotIn(vs ...int32) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldForksCount, vs...))
}

// ForksCountGT applies the GT predicate on the "forks_count" field.
func ForksCountGT(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldForksCount, v))
}

// ForksCountGTE applies the GTE predicate on the "forks_count" field.
func ForksCountGTE(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldForksCount, v))
}

// ForksCountLT applies the LT predicate on the "forks_count" field.
func ForksCountLT(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldForksCount, v))
}

// ForksCountLTE applies the LTE predicate on the "forks_count" field.
func ForksCountLTE(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldForksCount, v))
}

// OpenIssuesCountEQ applies the EQ predicate on the "open_issues_count" field.
func OpenIssuesCountEQ(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldOpenIssuesCount, v))
}

// OpenIssuesCountNEQ applies the NEQ predicate on the "open_issues_count" field.
func OpenIssuesCountNEQ(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldOpenIssuesCount, v))
}

// OpenIssuesCountIn applies the In predicate on the "open_issues_count" field.
func OpenIssuesCountIn(vs ...int32) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldOpenIssuesCount, vs...))
}

// OpenIssuesCountNotIn applies the NotIn predicate on the "open_issues_count" field.
func OpenIssuesCountNotIn(vs ...int32) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldOpenIssuesCount, vs...))
}

// OpenIssuesCountGT applies the GT predicate on the "open_issues_count" field.
func OpenIssuesCountGT(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldOpenIssuesCount, v))
}

// OpenIssuesCountGTE applies the GTE predicate on the "open_issues_count" field.
func OpenIssuesCountGTE(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldOpenIssuesCount, v))
}

// OpenIssuesCountLT applies the LT predicate on the "open_issues_count" field.
func OpenIssuesCountLT(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldOpenIssuesCount, v))
}

// OpenIssuesCountLTE applies the LTE predicate on the "open_issues_count" field.
func OpenIssuesCountLTE(v int32) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldOpenIssuesCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldUpdatedAt, v))
}

// PushedAtEQ applies the EQ predicate on the "pushed_at" field.
func PushedAtEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldEQ(FieldPushedAt, v))
}

// PushedAtNEQ applies the NEQ predicate on the "pushed_at" field.
func PushedAtNEQ(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNEQ(FieldPushedAt, v))
}

// PushedAtIn applies the In predicate on the "pushed_at" field.
func PushedAtIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldIn(FieldPushedAt, vs...))
}

// PushedAtNotIn applies the NotIn predicate on the "pushed_at" field.
func PushedAtNotIn(vs ...time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldNotIn(FieldPushedAt, vs...))
}

// PushedAtGT applies the GT predicate on the "pushed_at" field.
func PushedAtGT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGT(FieldPushedAt, v))
}

// PushedAtGTE applies the GTE predicate on the "pushed_at" field.
func PushedAtGTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldGTE(FieldPushedAt, v))
}

// PushedAtLT applies the LT predicate on the "pushed_at" field.
func PushedAtLT(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLT(FieldPushedAt, v))
}

// PushedAtLTE applies the LTE predicate on the "pushed_at" field.
func PushedAtLTE(v time.Time) predicate.Repository {
	return predicate.Repository(sql.FieldLTE(FieldPushedAt, v))
}

// PushedAtIsNil applies the IsNil predicate on the "pushed_at" field.
func PushedAtIsNil() predicate.Repository {
	return predicate.Repository(sql.FieldIsNull(FieldPushedAt))
}

// PushedAtNotNil applies the NotNil predicate on the "pushed_at" field.
func PushedAtNotNil() predicate.Repository {
	return predicate.Repository(sql.FieldNotNull(FieldPushedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Repository) predicate.Repository {
	return predicate.Repository(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Repository) predicate.Repository {
	return predicate.Repository(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Repository) predicate.Repository {
	return predicate.Repository(sql.NotPredicates(p))
}
