// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: issues/v1/repository.proto

package issuesv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/kongken/datasrv/pkg/proto/issues/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RepositoryServiceName is the fully-qualified name of the RepositoryService service.
	RepositoryServiceName = "issues.v1.RepositoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RepositoryServiceCreateRepositoryProcedure is the fully-qualified name of the RepositoryService's
	// CreateRepository RPC.
	RepositoryServiceCreateRepositoryProcedure = "/issues.v1.RepositoryService/CreateRepository"
	// RepositoryServiceGetRepositoryProcedure is the fully-qualified name of the RepositoryService's
	// GetRepository RPC.
	RepositoryServiceGetRepositoryProcedure = "/issues.v1.RepositoryService/GetRepository"
	// RepositoryServiceListRepositoriesProcedure is the fully-qualified name of the RepositoryService's
	// ListRepositories RPC.
	RepositoryServiceListRepositoriesProcedure = "/issues.v1.RepositoryService/ListRepositories"
	// RepositoryServiceUpdateRepositoryProcedure is the fully-qualified name of the RepositoryService's
	// UpdateRepository RPC.
	RepositoryServiceUpdateRepositoryProcedure = "/issues.v1.RepositoryService/UpdateRepository"
	// RepositoryServiceDeleteRepositoryProcedure is the fully-qualified name of the RepositoryService's
	// DeleteRepository RPC.
	RepositoryServiceDeleteRepositoryProcedure = "/issues.v1.RepositoryService/DeleteRepository"
)

// RepositoryServiceClient is a client for the issues.v1.RepositoryService service.
type RepositoryServiceClient interface {
	// Create 创建仓库。
	CreateRepository(context.Context, *connect.Request[v1.CreateRepositoryRequest]) (*connect.Response[v1.CreateRepositoryResponse], error)
	// Get 查询单个仓库。
	GetRepository(context.Context, *connect.Request[v1.GetRepositoryRequest]) (*connect.Response[v1.GetRepositoryResponse], error)
	// List 查询仓库列表。
	ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error)
	// Update 更新仓库。
	UpdateRepository(context.Context, *connect.Request[v1.UpdateRepositoryRequest]) (*connect.Response[v1.UpdateRepositoryResponse], error)
	// Delete 删除仓库。
	DeleteRepository(context.Context, *connect.Request[v1.DeleteRepositoryRequest]) (*connect.Response[v1.DeleteRepositoryResponse], error)
}

// NewRepositoryServiceClient constructs a client for the issues.v1.RepositoryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRepositoryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RepositoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	repositoryServiceMethods := v1.File_issues_v1_repository_proto.Services().ByName("RepositoryService").Methods()
	return &repositoryServiceClient{
		createRepository: connect.NewClient[v1.CreateRepositoryRequest, v1.CreateRepositoryResponse](
			httpClient,
			baseURL+RepositoryServiceCreateRepositoryProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("CreateRepository")),
			connect.WithClientOptions(opts...),
		),
		getRepository: connect.NewClient[v1.GetRepositoryRequest, v1.GetRepositoryResponse](
			httpClient,
			baseURL+RepositoryServiceGetRepositoryProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("GetRepository")),
			connect.WithClientOptions(opts...),
		),
		listRepositories: connect.NewClient[v1.ListRepositoriesRequest, v1.ListRepositoriesResponse](
			httpClient,
			baseURL+RepositoryServiceListRepositoriesProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("ListRepositories")),
			connect.WithClientOptions(opts...),
		),
		updateRepository: connect.NewClient[v1.UpdateRepositoryRequest, v1.UpdateRepositoryResponse](
			httpClient,
			baseURL+RepositoryServiceUpdateRepositoryProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("UpdateRepository")),
			connect.WithClientOptions(opts...),
		),
		deleteRepository: connect.NewClient[v1.DeleteRepositoryRequest, v1.DeleteRepositoryResponse](
			httpClient,
			baseURL+RepositoryServiceDeleteRepositoryProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("DeleteRepository")),
			connect.WithClientOptions(opts...),
		),
	}
}

// repositoryServiceClient implements RepositoryServiceClient.
type repositoryServiceClient struct {
	createRepository *connect.Client[v1.CreateRepositoryRequest, v1.CreateRepositoryResponse]
	getRepository    *connect.Client[v1.GetRepositoryRequest, v1.GetRepositoryResponse]
	listRepositories *connect.Client[v1.ListRepositoriesRequest, v1.ListRepositoriesResponse]
	updateRepository *connect.Client[v1.UpdateRepositoryRequest, v1.UpdateRepositoryResponse]
	deleteRepository *connect.Client[v1.DeleteRepositoryRequest, v1.DeleteRepositoryResponse]
}

// CreateRepository calls issues.v1.RepositoryService.CreateRepository.
func (c *repositoryServiceClient) CreateRepository(ctx context.Context, req *connect.Request[v1.CreateRepositoryRequest]) (*connect.Response[v1.CreateRepositoryResponse], error) {
	return c.createRepository.CallUnary(ctx, req)
}

// GetRepository calls issues.v1.RepositoryService.GetRepository.
func (c *repositoryServiceClient) GetRepository(ctx context.Context, req *connect.Request[v1.GetRepositoryRequest]) (*connect.Response[v1.GetRepositoryResponse], error) {
	return c.getRepository.CallUnary(ctx, req)
}

// ListRepositories calls issues.v1.RepositoryService.ListRepositories.
func (c *repositoryServiceClient) ListRepositories(ctx context.Context, req *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error) {
	return c.listRepositories.CallUnary(ctx, req)
}

// UpdateRepository calls issues.v1.RepositoryService.UpdateRepository.
func (c *repositoryServiceClient) UpdateRepository(ctx context.Context, req *connect.Request[v1.UpdateRepositoryRequest]) (*connect.Response[v1.UpdateRepositoryResponse], error) {
	return c.updateRepository.CallUnary(ctx, req)
}

// DeleteRepository calls issues.v1.RepositoryService.DeleteRepository.
func (c *repositoryServiceClient) DeleteRepository(ctx context.Context, req *connect.Request[v1.DeleteRepositoryRequest]) (*connect.Response[v1.DeleteRepositoryResponse], error) {
	return c.deleteRepository.CallUnary(ctx, req)
}

// RepositoryServiceHandler is an implementation of the issues.v1.RepositoryService service.
type RepositoryServiceHandler interface {
	// Create 创建仓库。
	CreateRepository(context.Context, *connect.Request[v1.CreateRepositoryRequest]) (*connect.Response[v1.CreateRepositoryResponse], error)
	// Get 查询单个仓库。
	GetRepository(context.Context, *connect.Request[v1.GetRepositoryRequest]) (*connect.Response[v1.GetRepositoryResponse], error)
	// List 查询仓库列表。
	ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error)
	// Update 更新仓库。
	UpdateRepository(context.Context, *connect.Request[v1.UpdateRepositoryRequest]) (*connect.Response[v1.UpdateRepositoryResponse], error)
	// Delete 删除仓库。
	DeleteRepository(context.Context, *connect.Request[v1.DeleteRepositoryRequest]) (*connect.Response[v1.DeleteRepositoryResponse], error)
}

// NewRepositoryServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRepositoryServiceHandler(svc RepositoryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	repositoryServiceMethods := v1.File_issues_v1_repository_proto.Services().ByName("RepositoryService").Methods()
	repositoryServiceCreateRepositoryHandler := connect.NewUnaryHandler(
		RepositoryServiceCreateRepositoryProcedure,
		svc.CreateRepository,
		connect.WithSchema(repositoryServiceMethods.ByName("CreateRepository")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceGetRepositoryHandler := connect.NewUnaryHandler(
		RepositoryServiceGetRepositoryProcedure,
		svc.GetRepository,
		connect.WithSchema(repositoryServiceMethods.ByName("GetRepository")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceListRepositoriesHandler := connect.NewUnaryHandler(
		RepositoryServiceListRepositoriesProcedure,
		svc.ListRepositories,
		connect.WithSchema(repositoryServiceMethods.ByName("ListRepositories")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceUpdateRepositoryHandler := connect.NewUnaryHandler(
		RepositoryServiceUpdateRepositoryProcedure,
		svc.UpdateRepository,
		connect.WithSchema(repositoryServiceMethods.ByName("UpdateRepository")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceDeleteRepositoryHandler := connect.NewUnaryHandler(
		RepositoryServiceDeleteRepositoryProcedure,
		svc.DeleteRepository,
		connect.WithSchema(repositoryServiceMethods.ByName("DeleteRepository")),
		connect.WithHandlerOptions(opts...),
	)
	return "/issues.v1.RepositoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RepositoryServiceCreateRepositoryProcedure:
			repositoryServiceCreateRepositoryHandler.ServeHTTP(w, r)
		case RepositoryServiceGetRepositoryProcedure:
			repositoryServiceGetRepositoryHandler.ServeHTTP(w, r)
		case RepositoryServiceListRepositoriesProcedure:
			repositoryServiceListRepositoriesHandler.ServeHTTP(w, r)
		case RepositoryServiceUpdateRepositoryProcedure:
			repositoryServiceUpdateRepositoryHandler.ServeHTTP(w, r)
		case RepositoryServiceDeleteRepositoryProcedure:
			repositoryServiceDeleteRepositoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRepositoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRepositoryServiceHandler struct{}

func (UnimplementedRepositoryServiceHandler) CreateRepository(context.Context, *connect.Request[v1.CreateRepositoryRequest]) (*connect.Response[v1.CreateRepositoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("issues.v1.RepositoryService.CreateRepository is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) GetRepository(context.Context, *connect.Request[v1.GetRepositoryRequest]) (*connect.Response[v1.GetRepositoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("issues.v1.RepositoryService.GetRepository is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("issues.v1.RepositoryService.ListRepositories is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) UpdateRepository(context.Context, *connect.Request[v1.UpdateRepositoryRequest]) (*connect.Response[v1.UpdateRepositoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("issues.v1.RepositoryService.UpdateRepository is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) DeleteRepository(context.Context, *connect.Request[v1.DeleteRepositoryRequest]) (*connect.Response[v1.DeleteRepositoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("issues.v1.RepositoryService.DeleteRepository is not implemented"))
}
