// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: issues/v1/issue.proto

package issuesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IssueSyncAdminService_SyncIssues_FullMethodName       = "/issues.v1.IssueSyncAdminService/SyncIssues"
	IssueSyncAdminService_GetSyncConfig_FullMethodName    = "/issues.v1.IssueSyncAdminService/GetSyncConfig"
	IssueSyncAdminService_UpdateSyncConfig_FullMethodName = "/issues.v1.IssueSyncAdminService/UpdateSyncConfig"
	IssueSyncAdminService_GetSyncStatus_FullMethodName    = "/issues.v1.IssueSyncAdminService/GetSyncStatus"
)

// IssueSyncAdminServiceClient is the client API for IssueSyncAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IssueSyncAdminServiceClient interface {
	SyncIssues(ctx context.Context, in *SyncIssuesRequest, opts ...grpc.CallOption) (*SyncIssuesResponse, error)
	GetSyncConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSyncConfigResponse, error)
	UpdateSyncConfig(ctx context.Context, in *UpdateSyncConfigRequest, opts ...grpc.CallOption) (*GetSyncConfigResponse, error)
	GetSyncStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSyncStatusResponse, error)
}

type issueSyncAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIssueSyncAdminServiceClient(cc grpc.ClientConnInterface) IssueSyncAdminServiceClient {
	return &issueSyncAdminServiceClient{cc}
}

func (c *issueSyncAdminServiceClient) SyncIssues(ctx context.Context, in *SyncIssuesRequest, opts ...grpc.CallOption) (*SyncIssuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncIssuesResponse)
	err := c.cc.Invoke(ctx, IssueSyncAdminService_SyncIssues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSyncAdminServiceClient) GetSyncConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSyncConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncConfigResponse)
	err := c.cc.Invoke(ctx, IssueSyncAdminService_GetSyncConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSyncAdminServiceClient) UpdateSyncConfig(ctx context.Context, in *UpdateSyncConfigRequest, opts ...grpc.CallOption) (*GetSyncConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncConfigResponse)
	err := c.cc.Invoke(ctx, IssueSyncAdminService_UpdateSyncConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *issueSyncAdminServiceClient) GetSyncStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSyncStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncStatusResponse)
	err := c.cc.Invoke(ctx, IssueSyncAdminService_GetSyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssueSyncAdminServiceServer is the server API for IssueSyncAdminService service.
// All implementations must embed UnimplementedIssueSyncAdminServiceServer
// for forward compatibility.
type IssueSyncAdminServiceServer interface {
	SyncIssues(context.Context, *SyncIssuesRequest) (*SyncIssuesResponse, error)
	GetSyncConfig(context.Context, *emptypb.Empty) (*GetSyncConfigResponse, error)
	UpdateSyncConfig(context.Context, *UpdateSyncConfigRequest) (*GetSyncConfigResponse, error)
	GetSyncStatus(context.Context, *emptypb.Empty) (*GetSyncStatusResponse, error)
	mustEmbedUnimplementedIssueSyncAdminServiceServer()
}

// UnimplementedIssueSyncAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIssueSyncAdminServiceServer struct{}

func (UnimplementedIssueSyncAdminServiceServer) SyncIssues(context.Context, *SyncIssuesRequest) (*SyncIssuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncIssues not implemented")
}
func (UnimplementedIssueSyncAdminServiceServer) GetSyncConfig(context.Context, *emptypb.Empty) (*GetSyncConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncConfig not implemented")
}
func (UnimplementedIssueSyncAdminServiceServer) UpdateSyncConfig(context.Context, *UpdateSyncConfigRequest) (*GetSyncConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSyncConfig not implemented")
}
func (UnimplementedIssueSyncAdminServiceServer) GetSyncStatus(context.Context, *emptypb.Empty) (*GetSyncStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncStatus not implemented")
}
func (UnimplementedIssueSyncAdminServiceServer) mustEmbedUnimplementedIssueSyncAdminServiceServer() {}
func (UnimplementedIssueSyncAdminServiceServer) testEmbeddedByValue()                               {}

// UnsafeIssueSyncAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IssueSyncAdminServiceServer will
// result in compilation errors.
type UnsafeIssueSyncAdminServiceServer interface {
	mustEmbedUnimplementedIssueSyncAdminServiceServer()
}

func RegisterIssueSyncAdminServiceServer(s grpc.ServiceRegistrar, srv IssueSyncAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedIssueSyncAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IssueSyncAdminService_ServiceDesc, srv)
}

func _IssueSyncAdminService_SyncIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSyncAdminServiceServer).SyncIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSyncAdminService_SyncIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSyncAdminServiceServer).SyncIssues(ctx, req.(*SyncIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSyncAdminService_GetSyncConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSyncAdminServiceServer).GetSyncConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSyncAdminService_GetSyncConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSyncAdminServiceServer).GetSyncConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSyncAdminService_UpdateSyncConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSyncConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSyncAdminServiceServer).UpdateSyncConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSyncAdminService_UpdateSyncConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSyncAdminServiceServer).UpdateSyncConfig(ctx, req.(*UpdateSyncConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IssueSyncAdminService_GetSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssueSyncAdminServiceServer).GetSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssueSyncAdminService_GetSyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssueSyncAdminServiceServer).GetSyncStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IssueSyncAdminService_ServiceDesc is the grpc.ServiceDesc for IssueSyncAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IssueSyncAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "issues.v1.IssueSyncAdminService",
	HandlerType: (*IssueSyncAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncIssues",
			Handler:    _IssueSyncAdminService_SyncIssues_Handler,
		},
		{
			MethodName: "GetSyncConfig",
			Handler:    _IssueSyncAdminService_GetSyncConfig_Handler,
		},
		{
			MethodName: "UpdateSyncConfig",
			Handler:    _IssueSyncAdminService_UpdateSyncConfig_Handler,
		},
		{
			MethodName: "GetSyncStatus",
			Handler:    _IssueSyncAdminService_GetSyncStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "issues/v1/issue.proto",
}
