// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/issue"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/milestone"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/user"
)

// Issue is the model entity for the Issue schema.
type Issue struct {
	config `json:"-"`
	// ID of the ent.
	// GitHub issue ID
	ID int64 `json:"id,omitempty"`
	// Issue number
	Number int32 `json:"number,omitempty"`
	// Issue title
	Title string `json:"title,omitempty"`
	// Issue body/description
	Body string `json:"body,omitempty"`
	// Issue state (open/closed)
	State string `json:"state,omitempty"`
	// Number of comments
	Comments int32 `json:"comments,omitempty"`
	// Issue HTML URL
	HTMLURL string `json:"html_url,omitempty"`
	// Whether the issue is locked
	Locked bool `json:"locked,omitempty"`
	// Creation time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Close time
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// Creator user ID
	UserID int64 `json:"user_id,omitempty"`
	// Milestone ID
	MilestoneID *int64 `json:"milestone_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IssueQuery when eager-loading is set.
	Edges        IssueEdges `json:"edges"`
	selectValues sql.SelectValues
}

// IssueEdges holds the relations/edges for other nodes in the graph.
type IssueEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Labels holds the value of the labels edge.
	Labels []*Label `json:"labels,omitempty"`
	// Assignees holds the value of the assignees edge.
	Assignees []*User `json:"assignees,omitempty"`
	// Milestone holds the value of the milestone edge.
	Milestone *Milestone `json:"milestone,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IssueEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// LabelsOrErr returns the Labels value or an error if the edge
// was not loaded in eager-loading.
func (e IssueEdges) LabelsOrErr() ([]*Label, error) {
	if e.loadedTypes[1] {
		return e.Labels, nil
	}
	return nil, &NotLoadedError{edge: "labels"}
}

// AssigneesOrErr returns the Assignees value or an error if the edge
// was not loaded in eager-loading.
func (e IssueEdges) AssigneesOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.Assignees, nil
	}
	return nil, &NotLoadedError{edge: "assignees"}
}

// MilestoneOrErr returns the Milestone value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IssueEdges) MilestoneOrErr() (*Milestone, error) {
	if e.Milestone != nil {
		return e.Milestone, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: milestone.Label}
	}
	return nil, &NotLoadedError{edge: "milestone"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Issue) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case issue.FieldLocked:
			values[i] = new(sql.NullBool)
		case issue.FieldID, issue.FieldNumber, issue.FieldComments, issue.FieldUserID, issue.FieldMilestoneID:
			values[i] = new(sql.NullInt64)
		case issue.FieldTitle, issue.FieldBody, issue.FieldState, issue.FieldHTMLURL:
			values[i] = new(sql.NullString)
		case issue.FieldCreatedAt, issue.FieldUpdatedAt, issue.FieldClosedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Issue fields.
func (_m *Issue) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case issue.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case issue.FieldNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				_m.Number = int32(value.Int64)
			}
		case issue.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case issue.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case issue.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case issue.FieldComments:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field comments", values[i])
			} else if value.Valid {
				_m.Comments = int32(value.Int64)
			}
		case issue.FieldHTMLURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field html_url", values[i])
			} else if value.Valid {
				_m.HTMLURL = value.String
			}
		case issue.FieldLocked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field locked", values[i])
			} else if value.Valid {
				_m.Locked = value.Bool
			}
		case issue.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case issue.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case issue.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case issue.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case issue.FieldMilestoneID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field milestone_id", values[i])
			} else if value.Valid {
				_m.MilestoneID = new(int64)
				*_m.MilestoneID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Issue.
// This includes values selected through modifiers, order, etc.
func (_m *Issue) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Issue entity.
func (_m *Issue) QueryUser() *UserQuery {
	return NewIssueClient(_m.config).QueryUser(_m)
}

// QueryLabels queries the "labels" edge of the Issue entity.
func (_m *Issue) QueryLabels() *LabelQuery {
	return NewIssueClient(_m.config).QueryLabels(_m)
}

// QueryAssignees queries the "assignees" edge of the Issue entity.
func (_m *Issue) QueryAssignees() *UserQuery {
	return NewIssueClient(_m.config).QueryAssignees(_m)
}

// QueryMilestone queries the "milestone" edge of the Issue entity.
func (_m *Issue) QueryMilestone() *MilestoneQuery {
	return NewIssueClient(_m.config).QueryMilestone(_m)
}

// Update returns a builder for updating this Issue.
// Note that you need to call Issue.Unwrap() before calling this method if this Issue
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Issue) Update() *IssueUpdateOne {
	return NewIssueClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Issue entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Issue) Unwrap() *Issue {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Issue is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Issue) String() string {
	var builder strings.Builder
	builder.WriteString("Issue(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("number=")
	builder.WriteString(fmt.Sprintf("%v", _m.Number))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("comments=")
	builder.WriteString(fmt.Sprintf("%v", _m.Comments))
	builder.WriteString(", ")
	builder.WriteString("html_url=")
	builder.WriteString(_m.HTMLURL)
	builder.WriteString(", ")
	builder.WriteString("locked=")
	builder.WriteString(fmt.Sprintf("%v", _m.Locked))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.MilestoneID; v != nil {
		builder.WriteString("milestone_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Issues is a parsable slice of Issue.
type Issues []*Issue
