// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/issue"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/label"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/milestone"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/user"
)

// IssueCreate is the builder for creating a Issue entity.
type IssueCreate struct {
	config
	mutation *IssueMutation
	hooks    []Hook
}

// SetNumber sets the "number" field.
func (_c *IssueCreate) SetNumber(v int32) *IssueCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *IssueCreate) SetTitle(v string) *IssueCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *IssueCreate) SetBody(v string) *IssueCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *IssueCreate) SetNillableBody(v *string) *IssueCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *IssueCreate) SetState(v string) *IssueCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *IssueCreate) SetNillableState(v *string) *IssueCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetComments sets the "comments" field.
func (_c *IssueCreate) SetComments(v int32) *IssueCreate {
	_c.mutation.SetComments(v)
	return _c
}

// SetNillableComments sets the "comments" field if the given value is not nil.
func (_c *IssueCreate) SetNillableComments(v *int32) *IssueCreate {
	if v != nil {
		_c.SetComments(*v)
	}
	return _c
}

// SetHTMLURL sets the "html_url" field.
func (_c *IssueCreate) SetHTMLURL(v string) *IssueCreate {
	_c.mutation.SetHTMLURL(v)
	return _c
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_c *IssueCreate) SetNillableHTMLURL(v *string) *IssueCreate {
	if v != nil {
		_c.SetHTMLURL(*v)
	}
	return _c
}

// SetLocked sets the "locked" field.
func (_c *IssueCreate) SetLocked(v bool) *IssueCreate {
	_c.mutation.SetLocked(v)
	return _c
}

// SetNillableLocked sets the "locked" field if the given value is not nil.
func (_c *IssueCreate) SetNillableLocked(v *bool) *IssueCreate {
	if v != nil {
		_c.SetLocked(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IssueCreate) SetCreatedAt(v time.Time) *IssueCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IssueCreate) SetNillableCreatedAt(v *time.Time) *IssueCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IssueCreate) SetUpdatedAt(v time.Time) *IssueCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IssueCreate) SetNillableUpdatedAt(v *time.Time) *IssueCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetClosedAt sets the "closed_at" field.
func (_c *IssueCreate) SetClosedAt(v time.Time) *IssueCreate {
	_c.mutation.SetClosedAt(v)
	return _c
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_c *IssueCreate) SetNillableClosedAt(v *time.Time) *IssueCreate {
	if v != nil {
		_c.SetClosedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *IssueCreate) SetUserID(v int64) *IssueCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *IssueCreate) SetNillableUserID(v *int64) *IssueCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetMilestoneID sets the "milestone_id" field.
func (_c *IssueCreate) SetMilestoneID(v int64) *IssueCreate {
	_c.mutation.SetMilestoneID(v)
	return _c
}

// SetNillableMilestoneID sets the "milestone_id" field if the given value is not nil.
func (_c *IssueCreate) SetNillableMilestoneID(v *int64) *IssueCreate {
	if v != nil {
		_c.SetMilestoneID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IssueCreate) SetID(v int64) *IssueCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *IssueCreate) SetUser(v *User) *IssueCreate {
	return _c.SetUserID(v.ID)
}

// AddLabelIDs adds the "labels" edge to the Label entity by IDs.
func (_c *IssueCreate) AddLabelIDs(ids ...int64) *IssueCreate {
	_c.mutation.AddLabelIDs(ids...)
	return _c
}

// AddLabels adds the "labels" edges to the Label entity.
func (_c *IssueCreate) AddLabels(v ...*Label) *IssueCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLabelIDs(ids...)
}

// AddAssigneeIDs adds the "assignees" edge to the User entity by IDs.
func (_c *IssueCreate) AddAssigneeIDs(ids ...int64) *IssueCreate {
	_c.mutation.AddAssigneeIDs(ids...)
	return _c
}

// AddAssignees adds the "assignees" edges to the User entity.
func (_c *IssueCreate) AddAssignees(v ...*User) *IssueCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssigneeIDs(ids...)
}

// SetMilestone sets the "milestone" edge to the Milestone entity.
func (_c *IssueCreate) SetMilestone(v *Milestone) *IssueCreate {
	return _c.SetMilestoneID(v.ID)
}

// Mutation returns the IssueMutation object of the builder.
func (_c *IssueCreate) Mutation() *IssueMutation {
	return _c.mutation
}

// Save creates the Issue in the database.
func (_c *IssueCreate) Save(ctx context.Context) (*Issue, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IssueCreate) SaveX(ctx context.Context) *Issue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IssueCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IssueCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IssueCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := issue.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Comments(); !ok {
		v := issue.DefaultComments
		_c.mutation.SetComments(v)
	}
	if _, ok := _c.mutation.Locked(); !ok {
		v := issue.DefaultLocked
		_c.mutation.SetLocked(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := issue.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := issue.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IssueCreate) check() error {
	if _, ok := _c.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Issue.number"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Issue.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := issue.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Issue.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Issue.state"`)}
	}
	if _, ok := _c.mutation.Comments(); !ok {
		return &ValidationError{Name: "comments", err: errors.New(`ent: missing required field "Issue.comments"`)}
	}
	if _, ok := _c.mutation.Locked(); !ok {
		return &ValidationError{Name: "locked", err: errors.New(`ent: missing required field "Issue.locked"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Issue.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Issue.updated_at"`)}
	}
	return nil
}

func (_c *IssueCreate) sqlSave(ctx context.Context) (*Issue, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IssueCreate) createSpec() (*Issue, *sqlgraph.CreateSpec) {
	var (
		_node = &Issue{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(issue.Table, sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(issue.FieldNumber, field.TypeInt32, value)
		_node.Number = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(issue.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(issue.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(issue.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Comments(); ok {
		_spec.SetField(issue.FieldComments, field.TypeInt32, value)
		_node.Comments = value
	}
	if value, ok := _c.mutation.HTMLURL(); ok {
		_spec.SetField(issue.FieldHTMLURL, field.TypeString, value)
		_node.HTMLURL = value
	}
	if value, ok := _c.mutation.Locked(); ok {
		_spec.SetField(issue.FieldLocked, field.TypeBool, value)
		_node.Locked = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(issue.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(issue.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClosedAt(); ok {
		_spec.SetField(issue.FieldClosedAt, field.TypeTime, value)
		_node.ClosedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   issue.UserTable,
			Columns: []string{issue.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issue.LabelsTable,
			Columns: []string{issue.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssigneesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   issue.AssigneesTable,
			Columns: []string{issue.AssigneesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MilestoneIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   issue.MilestoneTable,
			Columns: []string{issue.MilestoneColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MilestoneID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IssueCreateBulk is the builder for creating many Issue entities in bulk.
type IssueCreateBulk struct {
	config
	err      error
	builders []*IssueCreate
}

// Save creates the Issue entities in the database.
func (_c *IssueCreateBulk) Save(ctx context.Context) ([]*Issue, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Issue, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IssueMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IssueCreateBulk) SaveX(ctx context.Context) []*Issue {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IssueCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IssueCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
