// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/issue"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/label"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/milestone"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/predicate"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/user"
)

// IssueQuery is the builder for querying Issue entities.
type IssueQuery struct {
	config
	ctx           *QueryContext
	order         []issue.OrderOption
	inters        []Interceptor
	predicates    []predicate.Issue
	withUser      *UserQuery
	withLabels    *LabelQuery
	withAssignees *UserQuery
	withMilestone *MilestoneQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IssueQuery builder.
func (_q *IssueQuery) Where(ps ...predicate.Issue) *IssueQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *IssueQuery) Limit(limit int) *IssueQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *IssueQuery) Offset(offset int) *IssueQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *IssueQuery) Unique(unique bool) *IssueQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *IssueQuery) Order(o ...issue.OrderOption) *IssueQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *IssueQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(issue.Table, issue.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, issue.UserTable, issue.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLabels chains the current query on the "labels" edge.
func (_q *IssueQuery) QueryLabels() *LabelQuery {
	query := (&LabelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(issue.Table, issue.FieldID, selector),
			sqlgraph.To(label.Table, label.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, issue.LabelsTable, issue.LabelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAssignees chains the current query on the "assignees" edge.
func (_q *IssueQuery) QueryAssignees() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(issue.Table, issue.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, issue.AssigneesTable, issue.AssigneesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMilestone chains the current query on the "milestone" edge.
func (_q *IssueQuery) QueryMilestone() *MilestoneQuery {
	query := (&MilestoneClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(issue.Table, issue.FieldID, selector),
			sqlgraph.To(milestone.Table, milestone.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, issue.MilestoneTable, issue.MilestoneColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Issue entity from the query.
// Returns a *NotFoundError when no Issue was found.
func (_q *IssueQuery) First(ctx context.Context) (*Issue, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{issue.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *IssueQuery) FirstX(ctx context.Context) *Issue {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Issue ID from the query.
// Returns a *NotFoundError when no Issue ID was found.
func (_q *IssueQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{issue.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *IssueQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Issue entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Issue entity is found.
// Returns a *NotFoundError when no Issue entities are found.
func (_q *IssueQuery) Only(ctx context.Context) (*Issue, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{issue.Label}
	default:
		return nil, &NotSingularError{issue.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *IssueQuery) OnlyX(ctx context.Context) *Issue {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Issue ID in the query.
// Returns a *NotSingularError when more than one Issue ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *IssueQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{issue.Label}
	default:
		err = &NotSingularError{issue.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *IssueQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Issues.
func (_q *IssueQuery) All(ctx context.Context) ([]*Issue, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Issue, *IssueQuery]()
	return withInterceptors[[]*Issue](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *IssueQuery) AllX(ctx context.Context) []*Issue {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Issue IDs.
func (_q *IssueQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(issue.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *IssueQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *IssueQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*IssueQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *IssueQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *IssueQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *IssueQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IssueQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *IssueQuery) Clone() *IssueQuery {
	if _q == nil {
		return nil
	}
	return &IssueQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]issue.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.Issue{}, _q.predicates...),
		withUser:      _q.withUser.Clone(),
		withLabels:    _q.withLabels.Clone(),
		withAssignees: _q.withAssignees.Clone(),
		withMilestone: _q.withMilestone.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IssueQuery) WithUser(opts ...func(*UserQuery)) *IssueQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithLabels tells the query-builder to eager-load the nodes that are connected to
// the "labels" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IssueQuery) WithLabels(opts ...func(*LabelQuery)) *IssueQuery {
	query := (&LabelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLabels = query
	return _q
}

// WithAssignees tells the query-builder to eager-load the nodes that are connected to
// the "assignees" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IssueQuery) WithAssignees(opts ...func(*UserQuery)) *IssueQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAssignees = query
	return _q
}

// WithMilestone tells the query-builder to eager-load the nodes that are connected to
// the "milestone" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *IssueQuery) WithMilestone(opts ...func(*MilestoneQuery)) *IssueQuery {
	query := (&MilestoneClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMilestone = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Number int32 `json:"number,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Issue.Query().
//		GroupBy(issue.FieldNumber).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *IssueQuery) GroupBy(field string, fields ...string) *IssueGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IssueGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = issue.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Number int32 `json:"number,omitempty"`
//	}
//
//	client.Issue.Query().
//		Select(issue.FieldNumber).
//		Scan(ctx, &v)
func (_q *IssueQuery) Select(fields ...string) *IssueSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &IssueSelect{IssueQuery: _q}
	sbuild.label = issue.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IssueSelect configured with the given aggregations.
func (_q *IssueQuery) Aggregate(fns ...AggregateFunc) *IssueSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *IssueQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !issue.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *IssueQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Issue, error) {
	var (
		nodes       = []*Issue{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withUser != nil,
			_q.withLabels != nil,
			_q.withAssignees != nil,
			_q.withMilestone != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Issue).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Issue{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *Issue, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLabels; query != nil {
		if err := _q.loadLabels(ctx, query, nodes,
			func(n *Issue) { n.Edges.Labels = []*Label{} },
			func(n *Issue, e *Label) { n.Edges.Labels = append(n.Edges.Labels, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAssignees; query != nil {
		if err := _q.loadAssignees(ctx, query, nodes,
			func(n *Issue) { n.Edges.Assignees = []*User{} },
			func(n *Issue, e *User) { n.Edges.Assignees = append(n.Edges.Assignees, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMilestone; query != nil {
		if err := _q.loadMilestone(ctx, query, nodes, nil,
			func(n *Issue, e *Milestone) { n.Edges.Milestone = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *IssueQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*Issue, init func(*Issue), assign func(*Issue, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Issue)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *IssueQuery) loadLabels(ctx context.Context, query *LabelQuery, nodes []*Issue, init func(*Issue), assign func(*Issue, *Label)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Issue)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Label(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(issue.LabelsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.issue_labels
		if fk == nil {
			return fmt.Errorf(`foreign-key "issue_labels" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "issue_labels" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *IssueQuery) loadAssignees(ctx context.Context, query *UserQuery, nodes []*Issue, init func(*Issue), assign func(*Issue, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Issue)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(issue.AssigneesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.issue_assignees
		if fk == nil {
			return fmt.Errorf(`foreign-key "issue_assignees" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "issue_assignees" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *IssueQuery) loadMilestone(ctx context.Context, query *MilestoneQuery, nodes []*Issue, init func(*Issue), assign func(*Issue, *Milestone)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Issue)
	for i := range nodes {
		if nodes[i].MilestoneID == nil {
			continue
		}
		fk := *nodes[i].MilestoneID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(milestone.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "milestone_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *IssueQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *IssueQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(issue.Table, issue.Columns, sqlgraph.NewFieldSpec(issue.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, issue.FieldID)
		for i := range fields {
			if fields[i] != issue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(issue.FieldUserID)
		}
		if _q.withMilestone != nil {
			_spec.Node.AddColumnOnce(issue.FieldMilestoneID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *IssueQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(issue.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = issue.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IssueGroupBy is the group-by builder for Issue entities.
type IssueGroupBy struct {
	selector
	build *IssueQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *IssueGroupBy) Aggregate(fns ...AggregateFunc) *IssueGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *IssueGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IssueQuery, *IssueGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *IssueGroupBy) sqlScan(ctx context.Context, root *IssueQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IssueSelect is the builder for selecting fields of Issue entities.
type IssueSelect struct {
	*IssueQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *IssueSelect) Aggregate(fns ...AggregateFunc) *IssueSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *IssueSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IssueQuery, *IssueSelect](ctx, _s.IssueQuery, _s, _s.inters, v)
}

func (_s *IssueSelect) sqlScan(ctx context.Context, root *IssueQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
