// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/milestone"
)

// MilestoneCreate is the builder for creating a Milestone entity.
type MilestoneCreate struct {
	config
	mutation *MilestoneMutation
	hooks    []Hook
}

// SetNumber sets the "number" field.
func (_c *MilestoneCreate) SetNumber(v int32) *MilestoneCreate {
	_c.mutation.SetNumber(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *MilestoneCreate) SetTitle(v string) *MilestoneCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *MilestoneCreate) SetDescription(v string) *MilestoneCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableDescription(v *string) *MilestoneCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *MilestoneCreate) SetState(v string) *MilestoneCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableState(v *string) *MilestoneCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetDueOn sets the "due_on" field.
func (_c *MilestoneCreate) SetDueOn(v time.Time) *MilestoneCreate {
	_c.mutation.SetDueOn(v)
	return _c
}

// SetNillableDueOn sets the "due_on" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableDueOn(v *time.Time) *MilestoneCreate {
	if v != nil {
		_c.SetDueOn(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MilestoneCreate) SetCreatedAt(v time.Time) *MilestoneCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableCreatedAt(v *time.Time) *MilestoneCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MilestoneCreate) SetUpdatedAt(v time.Time) *MilestoneCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MilestoneCreate) SetNillableUpdatedAt(v *time.Time) *MilestoneCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MilestoneCreate) SetID(v int64) *MilestoneCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MilestoneMutation object of the builder.
func (_c *MilestoneCreate) Mutation() *MilestoneMutation {
	return _c.mutation
}

// Save creates the Milestone in the database.
func (_c *MilestoneCreate) Save(ctx context.Context) (*Milestone, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MilestoneCreate) SaveX(ctx context.Context) *Milestone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MilestoneCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MilestoneCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MilestoneCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := milestone.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := milestone.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := milestone.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MilestoneCreate) check() error {
	if _, ok := _c.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Milestone.number"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Milestone.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := milestone.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Milestone.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Milestone.state"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Milestone.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Milestone.updated_at"`)}
	}
	return nil
}

func (_c *MilestoneCreate) sqlSave(ctx context.Context) (*Milestone, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MilestoneCreate) createSpec() (*Milestone, *sqlgraph.CreateSpec) {
	var (
		_node = &Milestone{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(milestone.Table, sqlgraph.NewFieldSpec(milestone.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Number(); ok {
		_spec.SetField(milestone.FieldNumber, field.TypeInt32, value)
		_node.Number = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(milestone.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(milestone.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(milestone.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.DueOn(); ok {
		_spec.SetField(milestone.FieldDueOn, field.TypeTime, value)
		_node.DueOn = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(milestone.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(milestone.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// MilestoneCreateBulk is the builder for creating many Milestone entities in bulk.
type MilestoneCreateBulk struct {
	config
	err      error
	builders []*MilestoneCreate
}

// Save creates the Milestone entities in the database.
func (_c *MilestoneCreateBulk) Save(ctx context.Context) ([]*Milestone, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Milestone, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MilestoneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MilestoneCreateBulk) SaveX(ctx context.Context) []*Milestone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MilestoneCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MilestoneCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
