// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/repository"
)

// RepositoryCreate is the builder for creating a Repository entity.
type RepositoryCreate struct {
	config
	mutation *RepositoryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *RepositoryCreate) SetName(v string) *RepositoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetFullName sets the "full_name" field.
func (_c *RepositoryCreate) SetFullName(v string) *RepositoryCreate {
	_c.mutation.SetFullName(v)
	return _c
}

// SetOwnerLogin sets the "owner_login" field.
func (_c *RepositoryCreate) SetOwnerLogin(v string) *RepositoryCreate {
	_c.mutation.SetOwnerLogin(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *RepositoryCreate) SetDescription(v string) *RepositoryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableDescription(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPrivate sets the "private" field.
func (_c *RepositoryCreate) SetPrivate(v bool) *RepositoryCreate {
	_c.mutation.SetPrivate(v)
	return _c
}

// SetNillablePrivate sets the "private" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillablePrivate(v *bool) *RepositoryCreate {
	if v != nil {
		_c.SetPrivate(*v)
	}
	return _c
}

// SetArchived sets the "archived" field.
func (_c *RepositoryCreate) SetArchived(v bool) *RepositoryCreate {
	_c.mutation.SetArchived(v)
	return _c
}

// SetNillableArchived sets the "archived" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableArchived(v *bool) *RepositoryCreate {
	if v != nil {
		_c.SetArchived(*v)
	}
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *RepositoryCreate) SetDisabled(v bool) *RepositoryCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableDisabled(v *bool) *RepositoryCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetHTMLURL sets the "html_url" field.
func (_c *RepositoryCreate) SetHTMLURL(v string) *RepositoryCreate {
	_c.mutation.SetHTMLURL(v)
	return _c
}

// SetNillableHTMLURL sets the "html_url" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableHTMLURL(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetHTMLURL(*v)
	}
	return _c
}

// SetDefaultBranch sets the "default_branch" field.
func (_c *RepositoryCreate) SetDefaultBranch(v string) *RepositoryCreate {
	_c.mutation.SetDefaultBranch(v)
	return _c
}

// SetNillableDefaultBranch sets the "default_branch" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableDefaultBranch(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetDefaultBranch(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *RepositoryCreate) SetLanguage(v string) *RepositoryCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableLanguage(v *string) *RepositoryCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetStargazersCount sets the "stargazers_count" field.
func (_c *RepositoryCreate) SetStargazersCount(v int32) *RepositoryCreate {
	_c.mutation.SetStargazersCount(v)
	return _c
}

// SetNillableStargazersCount sets the "stargazers_count" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableStargazersCount(v *int32) *RepositoryCreate {
	if v != nil {
		_c.SetStargazersCount(*v)
	}
	return _c
}

// SetForksCount sets the "forks_count" field.
func (_c *RepositoryCreate) SetForksCount(v int32) *RepositoryCreate {
	_c.mutation.SetForksCount(v)
	return _c
}

// SetNillableForksCount sets the "forks_count" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableForksCount(v *int32) *RepositoryCreate {
	if v != nil {
		_c.SetForksCount(*v)
	}
	return _c
}

// SetOpenIssuesCount sets the "open_issues_count" field.
func (_c *RepositoryCreate) SetOpenIssuesCount(v int32) *RepositoryCreate {
	_c.mutation.SetOpenIssuesCount(v)
	return _c
}

// SetNillableOpenIssuesCount sets the "open_issues_count" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableOpenIssuesCount(v *int32) *RepositoryCreate {
	if v != nil {
		_c.SetOpenIssuesCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RepositoryCreate) SetCreatedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableCreatedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RepositoryCreate) SetUpdatedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillableUpdatedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPushedAt sets the "pushed_at" field.
func (_c *RepositoryCreate) SetPushedAt(v time.Time) *RepositoryCreate {
	_c.mutation.SetPushedAt(v)
	return _c
}

// SetNillablePushedAt sets the "pushed_at" field if the given value is not nil.
func (_c *RepositoryCreate) SetNillablePushedAt(v *time.Time) *RepositoryCreate {
	if v != nil {
		_c.SetPushedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RepositoryCreate) SetID(v int64) *RepositoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RepositoryMutation object of the builder.
func (_c *RepositoryCreate) Mutation() *RepositoryMutation {
	return _c.mutation
}

// Save creates the Repository in the database.
func (_c *RepositoryCreate) Save(ctx context.Context) (*Repository, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepositoryCreate) SaveX(ctx context.Context) *Repository {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RepositoryCreate) defaults() {
	if _, ok := _c.mutation.Private(); !ok {
		v := repository.DefaultPrivate
		_c.mutation.SetPrivate(v)
	}
	if _, ok := _c.mutation.Archived(); !ok {
		v := repository.DefaultArchived
		_c.mutation.SetArchived(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := repository.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.DefaultBranch(); !ok {
		v := repository.DefaultDefaultBranch
		_c.mutation.SetDefaultBranch(v)
	}
	if _, ok := _c.mutation.StargazersCount(); !ok {
		v := repository.DefaultStargazersCount
		_c.mutation.SetStargazersCount(v)
	}
	if _, ok := _c.mutation.ForksCount(); !ok {
		v := repository.DefaultForksCount
		_c.mutation.SetForksCount(v)
	}
	if _, ok := _c.mutation.OpenIssuesCount(); !ok {
		v := repository.DefaultOpenIssuesCount
		_c.mutation.SetOpenIssuesCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := repository.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := repository.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepositoryCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Repository.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := repository.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Repository.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FullName(); !ok {
		return &ValidationError{Name: "full_name", err: errors.New(`ent: missing required field "Repository.full_name"`)}
	}
	if v, ok := _c.mutation.FullName(); ok {
		if err := repository.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Repository.full_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerLogin(); !ok {
		return &ValidationError{Name: "owner_login", err: errors.New(`ent: missing required field "Repository.owner_login"`)}
	}
	if v, ok := _c.mutation.OwnerLogin(); ok {
		if err := repository.OwnerLoginValidator(v); err != nil {
			return &ValidationError{Name: "owner_login", err: fmt.Errorf(`ent: validator failed for field "Repository.owner_login": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Private(); !ok {
		return &ValidationError{Name: "private", err: errors.New(`ent: missing required field "Repository.private"`)}
	}
	if _, ok := _c.mutation.Archived(); !ok {
		return &ValidationError{Name: "archived", err: errors.New(`ent: missing required field "Repository.archived"`)}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "Repository.disabled"`)}
	}
	if _, ok := _c.mutation.DefaultBranch(); !ok {
		return &ValidationError{Name: "default_branch", err: errors.New(`ent: missing required field "Repository.default_branch"`)}
	}
	if _, ok := _c.mutation.StargazersCount(); !ok {
		return &ValidationError{Name: "stargazers_count", err: errors.New(`ent: missing required field "Repository.stargazers_count"`)}
	}
	if _, ok := _c.mutation.ForksCount(); !ok {
		return &ValidationError{Name: "forks_count", err: errors.New(`ent: missing required field "Repository.forks_count"`)}
	}
	if _, ok := _c.mutation.OpenIssuesCount(); !ok {
		return &ValidationError{Name: "open_issues_count", err: errors.New(`ent: missing required field "Repository.open_issues_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Repository.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Repository.updated_at"`)}
	}
	return nil
}

func (_c *RepositoryCreate) sqlSave(ctx context.Context) (*Repository, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepositoryCreate) createSpec() (*Repository, *sqlgraph.CreateSpec) {
	var (
		_node = &Repository{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repository.Table, sqlgraph.NewFieldSpec(repository.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(repository.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.FullName(); ok {
		_spec.SetField(repository.FieldFullName, field.TypeString, value)
		_node.FullName = value
	}
	if value, ok := _c.mutation.OwnerLogin(); ok {
		_spec.SetField(repository.FieldOwnerLogin, field.TypeString, value)
		_node.OwnerLogin = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(repository.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Private(); ok {
		_spec.SetField(repository.FieldPrivate, field.TypeBool, value)
		_node.Private = value
	}
	if value, ok := _c.mutation.Archived(); ok {
		_spec.SetField(repository.FieldArchived, field.TypeBool, value)
		_node.Archived = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(repository.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.HTMLURL(); ok {
		_spec.SetField(repository.FieldHTMLURL, field.TypeString, value)
		_node.HTMLURL = value
	}
	if value, ok := _c.mutation.DefaultBranch(); ok {
		_spec.SetField(repository.FieldDefaultBranch, field.TypeString, value)
		_node.DefaultBranch = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(repository.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.StargazersCount(); ok {
		_spec.SetField(repository.FieldStargazersCount, field.TypeInt32, value)
		_node.StargazersCount = value
	}
	if value, ok := _c.mutation.ForksCount(); ok {
		_spec.SetField(repository.FieldForksCount, field.TypeInt32, value)
		_node.ForksCount = value
	}
	if value, ok := _c.mutation.OpenIssuesCount(); ok {
		_spec.SetField(repository.FieldOpenIssuesCount, field.TypeInt32, value)
		_node.OpenIssuesCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(repository.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(repository.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PushedAt(); ok {
		_spec.SetField(repository.FieldPushedAt, field.TypeTime, value)
		_node.PushedAt = &value
	}
	return _node, _spec
}

// RepositoryCreateBulk is the builder for creating many Repository entities in bulk.
type RepositoryCreateBulk struct {
	config
	err      error
	builders []*RepositoryCreate
}

// Save creates the Repository entities in the database.
func (_c *RepositoryCreateBulk) Save(ctx context.Context) ([]*Repository, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Repository, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepositoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepositoryCreateBulk) SaveX(ctx context.Context) []*Repository {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepositoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepositoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
