// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Issue is the predicate function for issue builders.
type Issue func(*sql.Selector)

// Label is the predicate function for label builders.
type Label func(*sql.Selector)

// Milestone is the predicate function for milestone builders.
type Milestone func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
