// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: feeds/v1/feed.proto

package feedsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeedSyncAdminService_ListFeedSources_FullMethodName   = "/feeds.v1.FeedSyncAdminService/ListFeedSources"
	FeedSyncAdminService_GetFeedSource_FullMethodName     = "/feeds.v1.FeedSyncAdminService/GetFeedSource"
	FeedSyncAdminService_CreateFeedSource_FullMethodName  = "/feeds.v1.FeedSyncAdminService/CreateFeedSource"
	FeedSyncAdminService_UpdateFeedSource_FullMethodName  = "/feeds.v1.FeedSyncAdminService/UpdateFeedSource"
	FeedSyncAdminService_DeleteFeedSource_FullMethodName  = "/feeds.v1.FeedSyncAdminService/DeleteFeedSource"
	FeedSyncAdminService_SyncFeeds_FullMethodName         = "/feeds.v1.FeedSyncAdminService/SyncFeeds"
	FeedSyncAdminService_GetFeedSyncStatus_FullMethodName = "/feeds.v1.FeedSyncAdminService/GetFeedSyncStatus"
)

// FeedSyncAdminServiceClient is the client API for FeedSyncAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedSyncAdminServiceClient interface {
	ListFeedSources(ctx context.Context, in *ListFeedSourcesRequest, opts ...grpc.CallOption) (*ListFeedSourcesResponse, error)
	GetFeedSource(ctx context.Context, in *GetFeedSourceRequest, opts ...grpc.CallOption) (*FeedSource, error)
	CreateFeedSource(ctx context.Context, in *CreateFeedSourceRequest, opts ...grpc.CallOption) (*FeedSource, error)
	UpdateFeedSource(ctx context.Context, in *UpdateFeedSourceRequest, opts ...grpc.CallOption) (*FeedSource, error)
	DeleteFeedSource(ctx context.Context, in *DeleteFeedSourceRequest, opts ...grpc.CallOption) (*DeleteFeedSourceResponse, error)
	SyncFeeds(ctx context.Context, in *SyncFeedsRequest, opts ...grpc.CallOption) (*SyncFeedsResponse, error)
	GetFeedSyncStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetFeedSyncStatusResponse, error)
}

type feedSyncAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedSyncAdminServiceClient(cc grpc.ClientConnInterface) FeedSyncAdminServiceClient {
	return &feedSyncAdminServiceClient{cc}
}

func (c *feedSyncAdminServiceClient) ListFeedSources(ctx context.Context, in *ListFeedSourcesRequest, opts ...grpc.CallOption) (*ListFeedSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedSourcesResponse)
	err := c.cc.Invoke(ctx, FeedSyncAdminService_ListFeedSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedSyncAdminServiceClient) GetFeedSource(ctx context.Context, in *GetFeedSourceRequest, opts ...grpc.CallOption) (*FeedSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedSource)
	err := c.cc.Invoke(ctx, FeedSyncAdminService_GetFeedSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedSyncAdminServiceClient) CreateFeedSource(ctx context.Context, in *CreateFeedSourceRequest, opts ...grpc.CallOption) (*FeedSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedSource)
	err := c.cc.Invoke(ctx, FeedSyncAdminService_CreateFeedSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedSyncAdminServiceClient) UpdateFeedSource(ctx context.Context, in *UpdateFeedSourceRequest, opts ...grpc.CallOption) (*FeedSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedSource)
	err := c.cc.Invoke(ctx, FeedSyncAdminService_UpdateFeedSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedSyncAdminServiceClient) DeleteFeedSource(ctx context.Context, in *DeleteFeedSourceRequest, opts ...grpc.CallOption) (*DeleteFeedSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFeedSourceResponse)
	err := c.cc.Invoke(ctx, FeedSyncAdminService_DeleteFeedSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedSyncAdminServiceClient) SyncFeeds(ctx context.Context, in *SyncFeedsRequest, opts ...grpc.CallOption) (*SyncFeedsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncFeedsResponse)
	err := c.cc.Invoke(ctx, FeedSyncAdminService_SyncFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedSyncAdminServiceClient) GetFeedSyncStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetFeedSyncStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedSyncStatusResponse)
	err := c.cc.Invoke(ctx, FeedSyncAdminService_GetFeedSyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedSyncAdminServiceServer is the server API for FeedSyncAdminService service.
// All implementations must embed UnimplementedFeedSyncAdminServiceServer
// for forward compatibility.
type FeedSyncAdminServiceServer interface {
	ListFeedSources(context.Context, *ListFeedSourcesRequest) (*ListFeedSourcesResponse, error)
	GetFeedSource(context.Context, *GetFeedSourceRequest) (*FeedSource, error)
	CreateFeedSource(context.Context, *CreateFeedSourceRequest) (*FeedSource, error)
	UpdateFeedSource(context.Context, *UpdateFeedSourceRequest) (*FeedSource, error)
	DeleteFeedSource(context.Context, *DeleteFeedSourceRequest) (*DeleteFeedSourceResponse, error)
	SyncFeeds(context.Context, *SyncFeedsRequest) (*SyncFeedsResponse, error)
	GetFeedSyncStatus(context.Context, *emptypb.Empty) (*GetFeedSyncStatusResponse, error)
	mustEmbedUnimplementedFeedSyncAdminServiceServer()
}

// UnimplementedFeedSyncAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedSyncAdminServiceServer struct{}

func (UnimplementedFeedSyncAdminServiceServer) ListFeedSources(context.Context, *ListFeedSourcesRequest) (*ListFeedSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeedSources not implemented")
}
func (UnimplementedFeedSyncAdminServiceServer) GetFeedSource(context.Context, *GetFeedSourceRequest) (*FeedSource, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedSource not implemented")
}
func (UnimplementedFeedSyncAdminServiceServer) CreateFeedSource(context.Context, *CreateFeedSourceRequest) (*FeedSource, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFeedSource not implemented")
}
func (UnimplementedFeedSyncAdminServiceServer) UpdateFeedSource(context.Context, *UpdateFeedSourceRequest) (*FeedSource, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFeedSource not implemented")
}
func (UnimplementedFeedSyncAdminServiceServer) DeleteFeedSource(context.Context, *DeleteFeedSourceRequest) (*DeleteFeedSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFeedSource not implemented")
}
func (UnimplementedFeedSyncAdminServiceServer) SyncFeeds(context.Context, *SyncFeedsRequest) (*SyncFeedsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncFeeds not implemented")
}
func (UnimplementedFeedSyncAdminServiceServer) GetFeedSyncStatus(context.Context, *emptypb.Empty) (*GetFeedSyncStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedSyncStatus not implemented")
}
func (UnimplementedFeedSyncAdminServiceServer) mustEmbedUnimplementedFeedSyncAdminServiceServer() {}
func (UnimplementedFeedSyncAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeFeedSyncAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedSyncAdminServiceServer will
// result in compilation errors.
type UnsafeFeedSyncAdminServiceServer interface {
	mustEmbedUnimplementedFeedSyncAdminServiceServer()
}

func RegisterFeedSyncAdminServiceServer(s grpc.ServiceRegistrar, srv FeedSyncAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedFeedSyncAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeedSyncAdminService_ServiceDesc, srv)
}

func _FeedSyncAdminService_ListFeedSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedSyncAdminServiceServer).ListFeedSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedSyncAdminService_ListFeedSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedSyncAdminServiceServer).ListFeedSources(ctx, req.(*ListFeedSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedSyncAdminService_GetFeedSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedSyncAdminServiceServer).GetFeedSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedSyncAdminService_GetFeedSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedSyncAdminServiceServer).GetFeedSource(ctx, req.(*GetFeedSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedSyncAdminService_CreateFeedSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeedSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedSyncAdminServiceServer).CreateFeedSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedSyncAdminService_CreateFeedSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedSyncAdminServiceServer).CreateFeedSource(ctx, req.(*CreateFeedSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedSyncAdminService_UpdateFeedSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeedSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedSyncAdminServiceServer).UpdateFeedSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedSyncAdminService_UpdateFeedSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedSyncAdminServiceServer).UpdateFeedSource(ctx, req.(*UpdateFeedSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedSyncAdminService_DeleteFeedSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFeedSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedSyncAdminServiceServer).DeleteFeedSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedSyncAdminService_DeleteFeedSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedSyncAdminServiceServer).DeleteFeedSource(ctx, req.(*DeleteFeedSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedSyncAdminService_SyncFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncFeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedSyncAdminServiceServer).SyncFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedSyncAdminService_SyncFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedSyncAdminServiceServer).SyncFeeds(ctx, req.(*SyncFeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedSyncAdminService_GetFeedSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedSyncAdminServiceServer).GetFeedSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedSyncAdminService_GetFeedSyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedSyncAdminServiceServer).GetFeedSyncStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FeedSyncAdminService_ServiceDesc is the grpc.ServiceDesc for FeedSyncAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedSyncAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feeds.v1.FeedSyncAdminService",
	HandlerType: (*FeedSyncAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFeedSources",
			Handler:    _FeedSyncAdminService_ListFeedSources_Handler,
		},
		{
			MethodName: "GetFeedSource",
			Handler:    _FeedSyncAdminService_GetFeedSource_Handler,
		},
		{
			MethodName: "CreateFeedSource",
			Handler:    _FeedSyncAdminService_CreateFeedSource_Handler,
		},
		{
			MethodName: "UpdateFeedSource",
			Handler:    _FeedSyncAdminService_UpdateFeedSource_Handler,
		},
		{
			MethodName: "DeleteFeedSource",
			Handler:    _FeedSyncAdminService_DeleteFeedSource_Handler,
		},
		{
			MethodName: "SyncFeeds",
			Handler:    _FeedSyncAdminService_SyncFeeds_Handler,
		},
		{
			MethodName: "GetFeedSyncStatus",
			Handler:    _FeedSyncAdminService_GetFeedSyncStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feeds/v1/feed.proto",
}

const (
	FeedQueryService_ListFeeds_FullMethodName        = "/feeds.v1.FeedQueryService/ListFeeds"
	FeedQueryService_ListFeedContents_FullMethodName = "/feeds.v1.FeedQueryService/ListFeedContents"
	FeedQueryService_GetFeedContent_FullMethodName   = "/feeds.v1.FeedQueryService/GetFeedContent"
)

// FeedQueryServiceClient is the client API for FeedQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeedQueryServiceClient interface {
	ListFeeds(ctx context.Context, in *ListFeedSourcesRequest, opts ...grpc.CallOption) (*ListFeedSourcesResponse, error)
	ListFeedContents(ctx context.Context, in *ListFeedContentsRequest, opts ...grpc.CallOption) (*ListFeedContentsResponse, error)
	GetFeedContent(ctx context.Context, in *GetFeedContentRequest, opts ...grpc.CallOption) (*GetFeedContentResponse, error)
}

type feedQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeedQueryServiceClient(cc grpc.ClientConnInterface) FeedQueryServiceClient {
	return &feedQueryServiceClient{cc}
}

func (c *feedQueryServiceClient) ListFeeds(ctx context.Context, in *ListFeedSourcesRequest, opts ...grpc.CallOption) (*ListFeedSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedSourcesResponse)
	err := c.cc.Invoke(ctx, FeedQueryService_ListFeeds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedQueryServiceClient) ListFeedContents(ctx context.Context, in *ListFeedContentsRequest, opts ...grpc.CallOption) (*ListFeedContentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeedContentsResponse)
	err := c.cc.Invoke(ctx, FeedQueryService_ListFeedContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedQueryServiceClient) GetFeedContent(ctx context.Context, in *GetFeedContentRequest, opts ...grpc.CallOption) (*GetFeedContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedContentResponse)
	err := c.cc.Invoke(ctx, FeedQueryService_GetFeedContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedQueryServiceServer is the server API for FeedQueryService service.
// All implementations must embed UnimplementedFeedQueryServiceServer
// for forward compatibility.
type FeedQueryServiceServer interface {
	ListFeeds(context.Context, *ListFeedSourcesRequest) (*ListFeedSourcesResponse, error)
	ListFeedContents(context.Context, *ListFeedContentsRequest) (*ListFeedContentsResponse, error)
	GetFeedContent(context.Context, *GetFeedContentRequest) (*GetFeedContentResponse, error)
	mustEmbedUnimplementedFeedQueryServiceServer()
}

// UnimplementedFeedQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeedQueryServiceServer struct{}

func (UnimplementedFeedQueryServiceServer) ListFeeds(context.Context, *ListFeedSourcesRequest) (*ListFeedSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeeds not implemented")
}
func (UnimplementedFeedQueryServiceServer) ListFeedContents(context.Context, *ListFeedContentsRequest) (*ListFeedContentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFeedContents not implemented")
}
func (UnimplementedFeedQueryServiceServer) GetFeedContent(context.Context, *GetFeedContentRequest) (*GetFeedContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedContent not implemented")
}
func (UnimplementedFeedQueryServiceServer) mustEmbedUnimplementedFeedQueryServiceServer() {}
func (UnimplementedFeedQueryServiceServer) testEmbeddedByValue()                          {}

// UnsafeFeedQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeedQueryServiceServer will
// result in compilation errors.
type UnsafeFeedQueryServiceServer interface {
	mustEmbedUnimplementedFeedQueryServiceServer()
}

func RegisterFeedQueryServiceServer(s grpc.ServiceRegistrar, srv FeedQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedFeedQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeedQueryService_ServiceDesc, srv)
}

func _FeedQueryService_ListFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedQueryServiceServer).ListFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedQueryService_ListFeeds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedQueryServiceServer).ListFeeds(ctx, req.(*ListFeedSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedQueryService_ListFeedContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeedContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedQueryServiceServer).ListFeedContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedQueryService_ListFeedContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedQueryServiceServer).ListFeedContents(ctx, req.(*ListFeedContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedQueryService_GetFeedContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedQueryServiceServer).GetFeedContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeedQueryService_GetFeedContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedQueryServiceServer).GetFeedContent(ctx, req.(*GetFeedContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeedQueryService_ServiceDesc is the grpc.ServiceDesc for FeedQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeedQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "feeds.v1.FeedQueryService",
	HandlerType: (*FeedQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFeeds",
			Handler:    _FeedQueryService_ListFeeds_Handler,
		},
		{
			MethodName: "ListFeedContents",
			Handler:    _FeedQueryService_ListFeedContents_Handler,
		},
		{
			MethodName: "GetFeedContent",
			Handler:    _FeedQueryService_GetFeedContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feeds/v1/feed.proto",
}
