// Code generated by ent, DO NOT EDIT.

package milestone

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/kongken/datasrv/service/datasrv/internal/dao/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldID, id))
}

// Number applies equality check predicate on the "number" field. It's identical to NumberEQ.
func Number(v int32) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldNumber, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldDescription, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldState, v))
}

// DueOn applies equality check predicate on the "due_on" field. It's identical to DueOnEQ.
func DueOn(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldDueOn, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldUpdatedAt, v))
}

// NumberEQ applies the EQ predicate on the "number" field.
func NumberEQ(v int32) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldNumber, v))
}

// NumberNEQ applies the NEQ predicate on the "number" field.
func NumberNEQ(v int32) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldNumber, v))
}

// NumberIn applies the In predicate on the "number" field.
func NumberIn(vs ...int32) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldNumber, vs...))
}

// NumberNotIn applies the NotIn predicate on the "number" field.
func NumberNotIn(vs ...int32) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldNumber, vs...))
}

// NumberGT applies the GT predicate on the "number" field.
func NumberGT(v int32) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldNumber, v))
}

// NumberGTE applies the GTE predicate on the "number" field.
func NumberGTE(v int32) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldNumber, v))
}

// NumberLT applies the LT predicate on the "number" field.
func NumberLT(v int32) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldNumber, v))
}

// NumberLTE applies the LTE predicate on the "number" field.
func NumberLTE(v int32) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldNumber, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Milestone {
	return predicate.Milestone(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Milestone {
	return predicate.Milestone(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldContainsFold(FieldDescription, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.Milestone {
	return predicate.Milestone(sql.FieldContainsFold(FieldState, v))
}

// DueOnEQ applies the EQ predicate on the "due_on" field.
func DueOnEQ(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldDueOn, v))
}

// DueOnNEQ applies the NEQ predicate on the "due_on" field.
func DueOnNEQ(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldDueOn, v))
}

// DueOnIn applies the In predicate on the "due_on" field.
func DueOnIn(vs ...time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldDueOn, vs...))
}

// DueOnNotIn applies the NotIn predicate on the "due_on" field.
func DueOnNotIn(vs ...time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldDueOn, vs...))
}

// DueOnGT applies the GT predicate on the "due_on" field.
func DueOnGT(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldDueOn, v))
}

// DueOnGTE applies the GTE predicate on the "due_on" field.
func DueOnGTE(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldDueOn, v))
}

// DueOnLT applies the LT predicate on the "due_on" field.
func DueOnLT(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldDueOn, v))
}

// DueOnLTE applies the LTE predicate on the "due_on" field.
func DueOnLTE(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldDueOn, v))
}

// DueOnIsNil applies the IsNil predicate on the "due_on" field.
func DueOnIsNil() predicate.Milestone {
	return predicate.Milestone(sql.FieldIsNull(FieldDueOn))
}

// DueOnNotNil applies the NotNil predicate on the "due_on" field.
func DueOnNotNil() predicate.Milestone {
	return predicate.Milestone(sql.FieldNotNull(FieldDueOn))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Milestone {
	return predicate.Milestone(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Milestone) predicate.Milestone {
	return predicate.Milestone(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Milestone) predicate.Milestone {
	return predicate.Milestone(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Milestone) predicate.Milestone {
	return predicate.Milestone(sql.NotPredicates(p))
}
