// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: blog/v1/post.proto

package blogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlogQueryService_ListPosts_FullMethodName     = "/blog.v1.BlogQueryService/ListPosts"
	BlogQueryService_GetPost_FullMethodName       = "/blog.v1.BlogQueryService/GetPost"
	BlogQueryService_ListComments_FullMethodName  = "/blog.v1.BlogQueryService/ListComments"
	BlogQueryService_CreateComment_FullMethodName = "/blog.v1.BlogQueryService/CreateComment"
)

// BlogQueryServiceClient is the client API for BlogQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogQueryServiceClient interface {
	ListPosts(ctx context.Context, in *ListBlogPostsRequest, opts ...grpc.CallOption) (*ListBlogPostsResponse, error)
	GetPost(ctx context.Context, in *GetBlogPostRequest, opts ...grpc.CallOption) (*GetBlogPostResponse, error)
	ListComments(ctx context.Context, in *ListBlogCommentsRequest, opts ...grpc.CallOption) (*ListBlogCommentsResponse, error)
	CreateComment(ctx context.Context, in *CreateBlogCommentRequest, opts ...grpc.CallOption) (*BlogComment, error)
}

type blogQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogQueryServiceClient(cc grpc.ClientConnInterface) BlogQueryServiceClient {
	return &blogQueryServiceClient{cc}
}

func (c *blogQueryServiceClient) ListPosts(ctx context.Context, in *ListBlogPostsRequest, opts ...grpc.CallOption) (*ListBlogPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlogPostsResponse)
	err := c.cc.Invoke(ctx, BlogQueryService_ListPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogQueryServiceClient) GetPost(ctx context.Context, in *GetBlogPostRequest, opts ...grpc.CallOption) (*GetBlogPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlogPostResponse)
	err := c.cc.Invoke(ctx, BlogQueryService_GetPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogQueryServiceClient) ListComments(ctx context.Context, in *ListBlogCommentsRequest, opts ...grpc.CallOption) (*ListBlogCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlogCommentsResponse)
	err := c.cc.Invoke(ctx, BlogQueryService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogQueryServiceClient) CreateComment(ctx context.Context, in *CreateBlogCommentRequest, opts ...grpc.CallOption) (*BlogComment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlogComment)
	err := c.cc.Invoke(ctx, BlogQueryService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogQueryServiceServer is the server API for BlogQueryService service.
// All implementations must embed UnimplementedBlogQueryServiceServer
// for forward compatibility.
type BlogQueryServiceServer interface {
	ListPosts(context.Context, *ListBlogPostsRequest) (*ListBlogPostsResponse, error)
	GetPost(context.Context, *GetBlogPostRequest) (*GetBlogPostResponse, error)
	ListComments(context.Context, *ListBlogCommentsRequest) (*ListBlogCommentsResponse, error)
	CreateComment(context.Context, *CreateBlogCommentRequest) (*BlogComment, error)
	mustEmbedUnimplementedBlogQueryServiceServer()
}

// UnimplementedBlogQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlogQueryServiceServer struct{}

func (UnimplementedBlogQueryServiceServer) ListPosts(context.Context, *ListBlogPostsRequest) (*ListBlogPostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPosts not implemented")
}
func (UnimplementedBlogQueryServiceServer) GetPost(context.Context, *GetBlogPostRequest) (*GetBlogPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPost not implemented")
}
func (UnimplementedBlogQueryServiceServer) ListComments(context.Context, *ListBlogCommentsRequest) (*ListBlogCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedBlogQueryServiceServer) CreateComment(context.Context, *CreateBlogCommentRequest) (*BlogComment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedBlogQueryServiceServer) mustEmbedUnimplementedBlogQueryServiceServer() {}
func (UnimplementedBlogQueryServiceServer) testEmbeddedByValue()                          {}

// UnsafeBlogQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogQueryServiceServer will
// result in compilation errors.
type UnsafeBlogQueryServiceServer interface {
	mustEmbedUnimplementedBlogQueryServiceServer()
}

func RegisterBlogQueryServiceServer(s grpc.ServiceRegistrar, srv BlogQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedBlogQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlogQueryService_ServiceDesc, srv)
}

func _BlogQueryService_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlogPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogQueryServiceServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogQueryService_ListPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogQueryServiceServer).ListPosts(ctx, req.(*ListBlogPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogQueryService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlogPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogQueryServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogQueryService_GetPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogQueryServiceServer).GetPost(ctx, req.(*GetBlogPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogQueryService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlogCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogQueryServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogQueryService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogQueryServiceServer).ListComments(ctx, req.(*ListBlogCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogQueryService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogQueryServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogQueryService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogQueryServiceServer).CreateComment(ctx, req.(*CreateBlogCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlogQueryService_ServiceDesc is the grpc.ServiceDesc for BlogQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlogQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.v1.BlogQueryService",
	HandlerType: (*BlogQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPosts",
			Handler:    _BlogQueryService_ListPosts_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _BlogQueryService_GetPost_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _BlogQueryService_ListComments_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _BlogQueryService_CreateComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/v1/post.proto",
}

const (
	BlogAdminService_CreatePost_FullMethodName    = "/blog.v1.BlogAdminService/CreatePost"
	BlogAdminService_UpdatePost_FullMethodName    = "/blog.v1.BlogAdminService/UpdatePost"
	BlogAdminService_DeletePost_FullMethodName    = "/blog.v1.BlogAdminService/DeletePost"
	BlogAdminService_GetComment_FullMethodName    = "/blog.v1.BlogAdminService/GetComment"
	BlogAdminService_UpdateComment_FullMethodName = "/blog.v1.BlogAdminService/UpdateComment"
	BlogAdminService_DeleteComment_FullMethodName = "/blog.v1.BlogAdminService/DeleteComment"
)

// BlogAdminServiceClient is the client API for BlogAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogAdminServiceClient interface {
	CreatePost(ctx context.Context, in *CreateBlogPostRequest, opts ...grpc.CallOption) (*BlogPost, error)
	UpdatePost(ctx context.Context, in *UpdateBlogPostRequest, opts ...grpc.CallOption) (*BlogPost, error)
	DeletePost(ctx context.Context, in *DeleteBlogPostRequest, opts ...grpc.CallOption) (*DeleteBlogPostResponse, error)
	GetComment(ctx context.Context, in *GetBlogCommentRequest, opts ...grpc.CallOption) (*GetBlogCommentResponse, error)
	UpdateComment(ctx context.Context, in *UpdateBlogCommentRequest, opts ...grpc.CallOption) (*BlogComment, error)
	DeleteComment(ctx context.Context, in *DeleteBlogCommentRequest, opts ...grpc.CallOption) (*DeleteBlogCommentResponse, error)
}

type blogAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogAdminServiceClient(cc grpc.ClientConnInterface) BlogAdminServiceClient {
	return &blogAdminServiceClient{cc}
}

func (c *blogAdminServiceClient) CreatePost(ctx context.Context, in *CreateBlogPostRequest, opts ...grpc.CallOption) (*BlogPost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlogPost)
	err := c.cc.Invoke(ctx, BlogAdminService_CreatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogAdminServiceClient) UpdatePost(ctx context.Context, in *UpdateBlogPostRequest, opts ...grpc.CallOption) (*BlogPost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlogPost)
	err := c.cc.Invoke(ctx, BlogAdminService_UpdatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogAdminServiceClient) DeletePost(ctx context.Context, in *DeleteBlogPostRequest, opts ...grpc.CallOption) (*DeleteBlogPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBlogPostResponse)
	err := c.cc.Invoke(ctx, BlogAdminService_DeletePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogAdminServiceClient) GetComment(ctx context.Context, in *GetBlogCommentRequest, opts ...grpc.CallOption) (*GetBlogCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlogCommentResponse)
	err := c.cc.Invoke(ctx, BlogAdminService_GetComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogAdminServiceClient) UpdateComment(ctx context.Context, in *UpdateBlogCommentRequest, opts ...grpc.CallOption) (*BlogComment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlogComment)
	err := c.cc.Invoke(ctx, BlogAdminService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogAdminServiceClient) DeleteComment(ctx context.Context, in *DeleteBlogCommentRequest, opts ...grpc.CallOption) (*DeleteBlogCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBlogCommentResponse)
	err := c.cc.Invoke(ctx, BlogAdminService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogAdminServiceServer is the server API for BlogAdminService service.
// All implementations must embed UnimplementedBlogAdminServiceServer
// for forward compatibility.
type BlogAdminServiceServer interface {
	CreatePost(context.Context, *CreateBlogPostRequest) (*BlogPost, error)
	UpdatePost(context.Context, *UpdateBlogPostRequest) (*BlogPost, error)
	DeletePost(context.Context, *DeleteBlogPostRequest) (*DeleteBlogPostResponse, error)
	GetComment(context.Context, *GetBlogCommentRequest) (*GetBlogCommentResponse, error)
	UpdateComment(context.Context, *UpdateBlogCommentRequest) (*BlogComment, error)
	DeleteComment(context.Context, *DeleteBlogCommentRequest) (*DeleteBlogCommentResponse, error)
	mustEmbedUnimplementedBlogAdminServiceServer()
}

// UnimplementedBlogAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlogAdminServiceServer struct{}

func (UnimplementedBlogAdminServiceServer) CreatePost(context.Context, *CreateBlogPostRequest) (*BlogPost, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedBlogAdminServiceServer) UpdatePost(context.Context, *UpdateBlogPostRequest) (*BlogPost, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedBlogAdminServiceServer) DeletePost(context.Context, *DeleteBlogPostRequest) (*DeleteBlogPostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedBlogAdminServiceServer) GetComment(context.Context, *GetBlogCommentRequest) (*GetBlogCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetComment not implemented")
}
func (UnimplementedBlogAdminServiceServer) UpdateComment(context.Context, *UpdateBlogCommentRequest) (*BlogComment, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedBlogAdminServiceServer) DeleteComment(context.Context, *DeleteBlogCommentRequest) (*DeleteBlogCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedBlogAdminServiceServer) mustEmbedUnimplementedBlogAdminServiceServer() {}
func (UnimplementedBlogAdminServiceServer) testEmbeddedByValue()                          {}

// UnsafeBlogAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogAdminServiceServer will
// result in compilation errors.
type UnsafeBlogAdminServiceServer interface {
	mustEmbedUnimplementedBlogAdminServiceServer()
}

func RegisterBlogAdminServiceServer(s grpc.ServiceRegistrar, srv BlogAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedBlogAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlogAdminService_ServiceDesc, srv)
}

func _BlogAdminService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogAdminServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogAdminService_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogAdminServiceServer).CreatePost(ctx, req.(*CreateBlogPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogAdminService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlogPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogAdminServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogAdminService_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogAdminServiceServer).UpdatePost(ctx, req.(*UpdateBlogPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogAdminService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlogPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogAdminServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogAdminService_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogAdminServiceServer).DeletePost(ctx, req.(*DeleteBlogPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogAdminService_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlogCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogAdminServiceServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogAdminService_GetComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogAdminServiceServer).GetComment(ctx, req.(*GetBlogCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogAdminService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlogCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogAdminServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogAdminService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogAdminServiceServer).UpdateComment(ctx, req.(*UpdateBlogCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogAdminService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlogCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogAdminServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogAdminService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogAdminServiceServer).DeleteComment(ctx, req.(*DeleteBlogCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlogAdminService_ServiceDesc is the grpc.ServiceDesc for BlogAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlogAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.v1.BlogAdminService",
	HandlerType: (*BlogAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _BlogAdminService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _BlogAdminService_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _BlogAdminService_DeletePost_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _BlogAdminService_GetComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _BlogAdminService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _BlogAdminService_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog/v1/post.proto",
}
